## Xcode & Swift Development
brew "xcodes"
brew "xcbeautify"
brew "mint"

## PostgreSQL
brew "postgresql"

## Databases
brew "redis"

## Document
brew "poppler"
brew "pandoc"

## AI
brew "ollama"

## CLI Tools
brew "yq"
brew "shellcheck"
brew "shfmt"

## Media
brew "ffmpeg"