# Formula

## Version Control
brew "git"
brew "gh"

## CI/CD
brew "act"

## Development Tools
brew "pipx"
brew "node"
brew "watchman"

## Xcode & Swift Development
brew "xcodes"
brew "xcbeautify"
brew "swiftgen"
brew "mint"
brew "cocoapods"

## Ruby Development
brew "rbenv"
brew "ruby-build"

## Linter
brew "yamllint"

## Utility
brew "fdupes"

## Editor
brew "neovim"

# Cask
cask "flutter"
cask "android-commandlinetools"
cask "android-studio"
cask "temurin"
cask "figma"
cask "cursor"
cask "discord"
cask "slack"
cask "zoom"
cask "notion"
cask "spotify"
