## Version Control
brew "git"
brew "gh"

## Development Tools
brew "node"
# brew "go"

tap "leoafarias/fvm"
brew "leoafarias/fvm/fvm"

## Xcode & Swift Development
# brew "xcodes"
# brew "xcbeautify"
# brew "mint"
# brew "cocoapods"

## Ruby
brew "rbenv"
brew "ruby-build"

## Utility
# brew "yamllint"
# brew "marp-cli"
brew "displayplacer"

## Cask
cask "visual-studio-code"
cask "cursor"
cask "android-studio"
cask "android-commandlinetools"
cask "temurin"
# cask "figma"
# cask "google-chrome"
# cask "chatgpt"
# cask "discord"
# cask "slack"
# cask "zoom"
# cask "notion"
# cask "spotify"
