# Formula
brew "git"
brew "gh"
brew "cocoapods"
brew "fastlane"
brew "act"
# swiftlintはXcodeインストール後にinstall.shで直接インストール
brew "fdupes"
brew "xcodes"

# Cask
cask "flutter"
cask "android-commandlinetools"
cask "android-studio"
cask "temurin" # JavaのOpenJDK実装
cask "google-chrome"
cask "slack"
cask "spotify"
cask "zoom"
cask "notion"
cask "figma"
cask "cursor"