name: 'Run Implementer'
description: 'Run an implementer for a single issue and clean up related events (requires jlo preinstalled)'
inputs:
  issue_file:
    description: 'Issue file path'
    required: true
  prompt_preview:
    description: 'Show prompts without executing'
    required: false
    default: 'false'
  target_branch:
    description: 'Target branch for implementer output'
    required: true
runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      env:
        ISSUE_FILE: ${{ inputs.issue_file }}
        TARGET_BRANCH: ${{ inputs.target_branch }}
      run: |
        if [ -z "$ISSUE_FILE" ]; then
          echo "::error::issue_file is required"
          exit 1
        fi
        if [ ! -f "$ISSUE_FILE" ]; then
          echo "::error::Issue file not found in repository: $ISSUE_FILE"
          exit 1
        fi
        if [ -z "$TARGET_BRANCH" ]; then
          echo "::error::target_branch is required"
          exit 1
        fi

    - name: Validate runtime prerequisites
      shell: bash
      env:
        PROMPT_PREVIEW: ${{ inputs.prompt_preview }}
      run: |
        if ! command -v jlo >/dev/null 2>&1; then
          echo "::error::jlo is not installed in PATH. Install jlo before calling this action."
          exit 1
        fi

        if [ "$PROMPT_PREVIEW" != "true" ]; then
          if [ -z "$(git config user.name || true)" ] || [ -z "$(git config user.email || true)" ]; then
            echo "::error::Git identity is not configured. Run configure-git before non-preview implementer execution."
            exit 1
          fi
        fi

    - name: Run implementers
      shell: bash
      env:
        ISSUE_FILE: ${{ inputs.issue_file }}
        PROMPT_PREVIEW: ${{ inputs.prompt_preview }}
        TARGET_BRANCH: ${{ inputs.target_branch }}
      run: |
        args=("$ISSUE_FILE")
        [ "$PROMPT_PREVIEW" = "true" ] && args+=("--prompt-preview")
        jlo run implementers "${args[@]}" --branch "$TARGET_BRANCH"

    - name: Delete processed issue and source events
      if: ${{ inputs.prompt_preview != 'true' }}
      shell: bash
      env:
        ISSUE_FILE: ${{ inputs.issue_file }}
      run: jlo workflow workstreams clean issue "$ISSUE_FILE"
