# ==============================================================================
# Common Brew Casks
# ==============================================================================

# Networking & VPN
cask "tailscale"

# Window Management
cask "rectangle"

# Development Tools
cask "android-studio"
cask "android-commandlinetools"
cask "docker"

# Web Browsers & Communication
cask "google-chrome"
cask "slack"
cask "zoom"

# Note Taking & Documentation
cask "obsidian"

# Database Management
cask "pgadmin4"