## Xcode & Swift Development
brew "xcodes"
brew "xcbeautify"
brew "mint"

## PostgreSQL
brew "postgresql"

## Utility
brew "redis"
brew "poppler"
brew "pandoc"
brew "ollama"
brew "yq"
brew "shellcheck"
brew "shfmt"