## Version Control
# brew "git" # installed by scripts/git.sh
# brew "gh" # installed by scripts/gh.sh

## Development Tools
# brew "nvm" # installed by scripts/nodejs.sh
# brew "jq"   # installed by scripts/nodejs.sh
# brew "pnpm" # installed by scripts/nodejs/platform.sh
brew "go"
# tap "leoafarias/fvm" # installed by scripts/flutter.sh
# brew "leoafarias/fvm/fvm" # installed by scripts/flutter.sh

## Xcode & Swift Development
brew "xcodes"
brew "xcbeautify"
brew "mint"

## Ruby
# brew "rbenv" # installed by scripts/ruby.sh
# brew "openssl" # installed by scripts/ruby.sh

## Python
# brew "pyenv" # installed by scripts/python/platform.sh
# brew "uv" # installed by scripts/python/platform.sh

## PostgreSQL
brew "postgresql"

## Utility
brew "redis"
brew "jj"
brew "poppler"
brew "pandoc"
brew "ollama"
brew "yq"
# brew "just" # Installed via `make setup`
# brew "displayplacer" # installed by scripts/macos.sh

## Cask
# cask "visual-studio-code" # installed by scripts/vscode.sh
cask "android-studio"
cask "android-commandlinetools"
cask "google-chrome"
cask "slack"
cask "zoom"
cask "obsidian"
cask "docker"
cask "pgadmin4"
cask "tailscale"
cask "rectangle"
