name: Setup Ruby

on:
  push:
    branches: [ "main" ]
    paths:
      - 'dist/mev/ansible/playbook.yml'
      - 'dist/mev/ansible/ansible.cfg'
      - 'dist/mev/ansible/roles/ruby/**'
      - '.github/workflows/setup-ruby.yml'
      - '.github/actions/setup-base/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'dist/mev/ansible/playbook.yml'
      - 'dist/mev/ansible/ansible.cfg'
      - 'dist/mev/ansible/roles/ruby/**'
      - '.github/workflows/setup-ruby.yml'
      - '.github/actions/setup-base/**'
  workflow_dispatch:

jobs:
  setup-ruby:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup base environment
        uses: ./.github/actions/setup-base

      - name: Setup ruby
        run: just run make ruby
